---
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    env_file:
      - .env.override/brokers
    image: confluentinc/cp-enterprise-kafka:5.2.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      # KAFKA_BROKER_ID: 1
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${BROKER_HOST}:9092
      # KAFKA_LISTENERS: "http://0.0.0.0:9092"
      KAFKA_ZOOKEEPER_CONNECT: ${ZOOKEEPER_LIST}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_LOG_RETENTION_HOURS: 720
      KAFKA_LOG_RETENTION_BYTES: 4294967296
      KAFKA_LOG_SEGMENT_BYTES: 107374182
      KAFKA_LOG_RETENTION_CHECK_INTERVAL.MS: 60000
      KAFKA_LOG_SEGMENT_DELETE_DELAY.MS: 1000
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: ${BROKER_LIST}
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: ${ZOOKEEPER_LIST}
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
